FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./tests/*.csproj ./tests
RUN dotnet restore tests

# Copy everything else
COPY . ./
ENTRYPOINT ["dotnet", "test", "tests"]